// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf32R45VwV7qikONKp0v8bX47sGcmAbWs',
    appId: '1:491612470232:web:339e1fbac54f256bfdd0ad',
    messagingSenderId: '491612470232',
    projectId: 'warmmemo-1a485',
    authDomain: 'warmmemo-1a485.firebaseapp.com',
    storageBucket: 'warmmemo-1a485.firebasestorage.app',
    measurementId: 'G-P3ER388G7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdgCfMx6aHZd1JNoK6YpDWZJ119M7_pUQ',
    appId: '1:491612470232:android:936d81ea5cccf91cfdd0ad',
    messagingSenderId: '491612470232',
    projectId: 'warmmemo-1a485',
    storageBucket: 'warmmemo-1a485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWaex8UYk9N-COq0ooWVLiideVWpq4UYo',
    appId: '1:491612470232:ios:70e1f3f31d0654c1fdd0ad',
    messagingSenderId: '491612470232',
    projectId: 'warmmemo-1a485',
    storageBucket: 'warmmemo-1a485.firebasestorage.app',
    iosBundleId: 'com.example.warmmemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWaex8UYk9N-COq0ooWVLiideVWpq4UYo',
    appId: '1:491612470232:ios:70e1f3f31d0654c1fdd0ad',
    messagingSenderId: '491612470232',
    projectId: 'warmmemo-1a485',
    storageBucket: 'warmmemo-1a485.firebasestorage.app',
    iosBundleId: 'com.example.warmmemo',
  );
}
